config/routes.rb
Portfolio::Application.routes.draw do

  root 'pages#welcome', as: :welcome
  get '/portfolio' => 'pages#portfolio', as: :portfolio
  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def welcome
	end

	def portfolio
	end

	def about
	end
	
	def contact
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<ul class="social-media">
			<li>
				<a href="https://github.com/therladbsgh"><span style="color:black"><i class="fa fa-github fa-2x"></i></span></a>
			</li>
			<li>
				<a href="https://bitbucket.org/therladbsgh"><span style="color:black"><i class="fa fa-bitbucket fa-2x"></i></span></a>
			</li>
			<li>
				<a href="#"><span style="color:black"><i class="fa fa-twitter fa-2x"></i></span></a>
			</li>
		</ul>
		<p style="font-weight: 400;">© 2015 Andrew Kim</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Portfolio", welcome_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Welcome", welcome_path %></li>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "Blog", "http://therladbsgh.com" %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><a href="http://therladbsgh.com">Andrew Kim</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:500,100,300,700' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<div class="main-body" style="font-family: 'Roboto', sans-serif;">
	<div class="container">
		<h1>Hi, I'm Andrew Kim.</h1>
		<p>I'm just a high school student, just trying to learn and do random things.</p>
	</div>
</div>

app/views/pages/contact.html.erb
<div class="main-body" style="font-family: 'Roboto', sans-serif;">
	<div class="container">
		<h1>This is the contact page.</h1>
		<p>There is no contact whatsoever.</p>
		<p>Alternatively, you can just look at my footer.</p>
	</div>
</div>

app/views/pages/portfolio.html.erb
<div class="main-body">
	<div class="banner">
    	<ul>
    		<li>
  		      	<img src="https://dl.dropbox.com/s/op08qie8299oasj/Bolt%20Network.png" />
  		    </li>
        	<li>
        		<img src="https://dl.dropbox.com/s/ljsp3mqr8k1yzh1/Innovation%20Cloud.png" />
        	</li>
        	<li>
        		<img src="https://dl.dropbox.com/s/iuvxf91ditmcw5q/Broadway.png" />
        	</li>
    	</ul>
	</div>

	<div class="container-fluid" style="padding-top:50px">
		<div class="row">
			<div class="col-md-4">
				<a href="https://bolt-network-rails.herokuapp.com/">
					<img class="grid-image" src="https://dl.dropbox.com/s/op08qie8299oasj/Bolt%20Network.png" />
					<h2 style="text-align:center">Bolt Network</h2>
					<p style="text-align:center">A movie streaming service.</p>
				</a>
			</div>
			<div class="col-md-4">
				<a href="https://innovation-cloud-rails.herokuapp.com/">
					<img class="grid-image" src="https://dl.dropbox.com/s/ljsp3mqr8k1yzh1/Innovation%20Cloud.png" />
					<h2 style="text-align:center">Innovation Cloud</h2>
					<p style="text-align:center">A site for the Innovation Cloud Conference.</p>
				</a>
			</div>
			<div class="col-md-4">
				<a href="https://broadway-rails.herokuapp.com/">
					<img class="grid-image" src="https://dl.dropbox.com/s/iuvxf91ditmcw5q/Broadway.png" />
					<h2 style="text-align:center">Broadway</h2>
					<p style="text-align:center">A site for Broadway, a design startup.</p>
				</a>
			</div>
			<div class="col-md-4">
				<a href="https://bookmarks-rails-2633.herokuapp.com/books">
					<img class="grid-image" src="http://dl.dropbox.com/s/r1naqjk16w567os/Bookmarks.png" />
					<h2 style="text-align:center">Bookmarks</h2>
					<p style="text-align:center">A simple site showing bookmarks.</p>
				</a>
			</div>
			<div class="col-md-4">
				<a href="https://threadly-rails.herokuapp.com/">
					<img class="grid-image" src="https://dl.dropbox.com/s/o4nv2u0jtxoi5zd/Threadly.png" />
					<h2 style="text-align:center">Threadly</h2>
					<p style="text-align:center">A site to freely post whatever you want.</p>
				</a>
			</div>
			<div class="col-md-4">
				<a href="https://bass-music-rails.herokuapp.com/albums">
					<img class="grid-image" src="https://dl.dropbox.com/s/u7tfz64oqk36hhh/Bass%20Music.png" />
					<h2 style="text-align:center">Bass Music</h2>
					<p style="text-align:center">A music streaming service.</p>
				</a>
			</div>
		</div>
	</div>
</div>


<script src="//code.jquery.com/jquery-latest.min.js"></script>
<script src="//unslider.com/unslider.min.js"></script>

<script>
$(document).ready(function() {
    $('.banner').unslider({
		speed: 500,               //  The speed to animate each slide (in milliseconds)
		delay: 3000,              //  The delay between slide animations (in milliseconds)
		complete: function() {},  //  A function that gets called after every slide animation
		keys: true,               //  Enable keyboard (left, right) arrow shortcuts
		dots: false,               //  Display dot navigation
		fluid: true              //  Support responsive design. May break non-responsive designs
	});
});
</script>

app/views/pages/welcome.html.erb
<div class="main-body">
  <div id="welcome" class="jumbotron">
    <div id="welcome-container" class="container">
      <h1>Hello. My name is <span style="color:black">Andrew Kim</span> and I just try to build websites.</h1>
      <br><br>
      <!--<p><a class="btn-awesome" href="#" role="button">View my Work</a></p>-->
      <p><%= link_to "View my Work", portfolio_path, class: "btn-awesome", role: "button" %></p>
    </div>
  </div>
</div><!-- /.container -->